ENABLE_GPS_DEBUG_LINE = True
NB_OTHER_VEHICLES = 20
MAX_TIME_TO_UPDATE_TRAFFIC_LIGHT_IN_SECONDE = 10
MAX_TIME_TO_RESET_DURING_TRAINING_IN_SECONDE = 30
TRAINING = True
USE_LAST_WEIGHT = False
PRINT_DEBUG_OUTPUT_MODEL = True
